/**
 * Created by sunshine on 2017/3/15.
 */
const express = require('express')
const router = express.Router();
const route = require('./routes_admin')
var multipart=require('connect-multiparty');
var multipartMidd=multipart();

router.use(route.message)
router.use(route.message2)
router.get('/admin',route.showAdmin)
router.get('/test',route.showTest)
router.get('/details',route.showDetails)
router.get('/testing',route.showTesting)
router.get('/tests',route.showTestings)
router.get('/site',route.showInter)
router.get('/sites',route.showInters)
router.get('/teachers',route.showTeachers)
router.get('/teacher',route.showTeacher)
router.get('/class',route.showClasses)
router.get('/classes',route.showClassess)
router.get('/book',route.showBook)
router.get('/build',route.showbuild)
router.get('/refe',route.showreferen)
router.get('/summary',route.showsummary)
router.get('/classteach',route.showclassteach)
router.get('/double',route.showdouble)
router.get('/testteach',route.showtestteach)
router.get('/interteach',route.showinterTeach)
router.get('/achieve',route.showachieve)
router.get('/teachreform',route.showteachingreform)
router.get('/testreform',route.showtestreform)
router.get('/teachresult',route.showteachresult)
router.get('/teachcon',route.showteachcon)
router.get('/teachmove',route.showteachmove)
router.get('/teachmsg',route.showteachmsg)
router.get('/calendermsg',route.showcaldenrmsg)
router.get('/coursemsg',route.showcoursemsg)
router.get('/exercisemsg',route.showexercmsg)
router.get('/important',route.showimportsmsg)
router.get('/teachreforms',route.showteachrefs)
router.get('/testref',route.showtestref)
router.get('/interteachmain',route.showinterteachs)
router.get('/bookachieve',route.showachievebookimg)
router.get('/thesis',route.showthesis)
router.get('/teachieve',route.showteachieve)
router.get('/master',route.showmaster)
router.get('/doubleteacher',route.showdoubleteacher)
router.get('/doublebook',route.showdoublebook)
router.get('/doubleware',route.showdoubleware)
router.get('/doubleref',route.showdoubleref)
router.get('/doublecourse',route.showdoublecourse)
router.get('/doubletest',route.showdoubletest)

router.post('/addtest',route.testAdd)
router.post('/addsite',route.addSite)
router.post('/addteacher',route.addTeacher)
router.post('/addclass',route.addClass)
router.post('/addbuild',route.addbookbuild)
router.post('/addreferen',route.addrefe)
router.post('/addsummary',route.addsummary)
router.post('/addcal',route.addcal)
router.post('/addteachcourse',route.addteachcourse)
router.post('/addteaching',route.addteacing)
router.post('/addteachexer',route.addteachinghome)
router.post('/addimportant',route.addimports)
router.post('/addteachreform',route.addteachreform)
router.post('/addtestref',route.addtestreform)
router.post('/addinterteach',route.addintertach)
router.post('/addachieveimg',route.addachieveimg)
router.post('/addthesis',route.addthesis)
router.post('/addteachieve',route.addteachieves)
router.post('/addmaster',route.addmaster)
router.post('/adddoubleteacher',route.adddoubleteacher)
router.post('/adddoublebook',route.adddoublebooks)
router.post('/adddoubleware',route.adddoubleware)
router.post('/adddoubleref',route.adddoubleref)
router.post('/adddoublecourse',route.adddoublecourse)
router.post('/adddoubletest',route.adddoubletests)
module.exports = router